; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
;default_envs = dfrobot_firebeetle2_esp32e
; default_envs = firebeetle32
default_envs = seeed

; default options for each '[env:**]'
[env]
platform = espressif32 @ 6.13.0
framework = arduino
build_unflags = '-std=gnu++11'
build_flags = '-Wall' '-std=gnu++17'
lib_deps = https://github.com/skiphansen/chroma_shell.git


[env:seeed]
board = seeed_xiao_esp32s3
monitor_speed = 115200
